language: ruby

cache: bundler

services:
- postgresql
before_script:
- psql -c 'create database teller_test;' -U postgres
deploy:
  provider: heroku
env:
  COINCAP_PATH: https://api.coincap.io
  SHAPESHIFT_PATH: https://shapeshift.io

  global:
    secure: ZZsJqEYsT/Y84GxTjyBv9I+Af3Kqp6VqmNKUlp1GbghAq5c9kfzI+u4+YGTuNwwKdCd3J2jZpctImgju0DRPzMpaa7Uh5ON3spf8So6TqlXYrquy3+B2rCdidx9mMtBgtNtDZHzwrGZ83eHwLJuNREm0Q7F4mBoArmNxFSQLPXTzas4wObTCs7idPmrb7SdatPk4A6hbwL0IXPQltgTDXHJ6iFtBsFhvgRVjpQ+80/P3X7JcYuh5I+z6m+s+bFvmJZ6dz3+Rq8k7JFGdZavgafkYyjl9zKxUCpkG+bKCIBcqXniyZy5PWCOs4MD0wCM9OLvSmQai2q4H1X9gBNWVe0wd4Y0jOYI+1KMVOoLpR6Ib0WtklqkO/lQOE5OMswke56XUv6SLAsSC59GLi/eDseSOGQO5gu+kovDYt875/xbwscp3CW/vzhEjceiJX6lObhWyjvTaDXVvqW7350d2lef8k5xmknhRIZ0XGhf8RVoHE7fiuFCZJ8wT8j5ZUYjjEKTWs5DNM+q0ieieT6QvRUSoopjAnDKHKE46m61NF5XBf8OKbN3DzPfz7QCNxbg1ojJ45+VhwVRgNKkkOt0snaZc3oVl6OcoGiu2rhTWPulemrEJOlL4eNuLPDBYoElG2963iRDOluDPoULFCaxc3bcsUjj1j9QZVuJfcG7DH2c=
