language: ruby
services:
- postgresql
before_script:
- psql -c 'create database teller_test;' -U postgres
deploy:
  provider: heroku
env:
  secure: ZDDmtWJcu9N2C5xKnJilhbGCAGP1t+hbPLzwSn6i4mHnh+M+Hwh2kIk8MRPa5iF/oeG2juzMNE/N18xaDbQzqITnPIGAcXe8z6yFGCXdbsog7MLlxIpwwNCy+u/borm4S78c9WoVKnRmmPfc1UMH5nI/pxqqno+7wabdWcRvZxyxr7Jaqo/yzHwxbbUbr4Pbc+Atix5SQJJERqn//itEWcSjPfLqOa9vGxKEUNfC42pFSINs2z/qK14jG2nW333j0Y4qikMUHfuGekzUmVvTJrnz/0okY9cfS+eXNKpH4BgUUw15gK7omhovICuSpW4ElcoYSjKIeUzpwfw7odXHH/UgacNSSt1YkFh9LzEk/NrlmwvbHgE8bUDRMwxAjxPjFap2iKflGIU6+f+RXMsNrA3RHPOOyAB0GoK2tW6BKco36ielx/5oZ9EMbvTfbDj13CrKEkTYa1nGI3RIWUwci8xyh4GKQkYn9nbaiid5v2BiZJSU7Q5ayMJtTQqo28VwEpte4FASf7UusDIqzhTpMTie44nVE2oD0IWuEjZAeVWyAsNglhzICKNYN+AFFGwf/Xj5ssHMxzBu5+Kr6zgG/ICJ/KHwgI2Je6Vj3vyyszAnF3A1ne/PuGm7KzJ5gkOqCLTHlCsuYGLsxNv2nvdVuCqYVxN/n2Wp5ENeIuFr2F0=
