language: ruby
services:
- postgresql
before_script:
- psql -c 'create database teller_test;' -U postgres
deploy:
  provider: heroku
env:
  secure: FdqGmqwkqPb8lmLSVy96eSPcG0ncT5paJHCFv9PvcinLnUQQ+T/hhplUeJyVXr1tufZLdWGKNSuCzLR8K6hBdyKI0IH0VDa2B/UPw8wJRlZMILdN/af1S/qtZ1j0lbOmDLf9glCLEFjdsTHbUfLprwrsAFDJvaEvFHtn+Ujblv2jQSicdPkxvxXm1jFw860ezgVA8jSDGxIC3AP9C2sh65DZAkcaqoeNaEcP3lqkoxi6MJzEQ3TfngApWoev34EJ4HhxIrYipNYIJ3ifjxRzIvZA1M7O+Ywpr7HyJ7gI+Pqrz+NZtpMquUx2I30rmk0eZOG0QgKxQcZ7/1ZXNzU9776rsoOGQTCncs3kdCU/lGzwj/5Ri65qgMPIeQN7xjLsEUYBHV48gmmivaWtKD6eOV52dvMKMkEQYiusy55a6ls1NOwuxI0vYhoH38+9XAJXyzd4Utj5ERVKFTCDPQBtQ9ohjZwa5N63ZqyVMH/z15sRE0UN88ENGUR13s7voNqGkgCbFc3dUvB5UDBCCHxxB4JISKNZsQsvY3wnctw2KCTAI2P5ZIzutHgzrwUUf9sVUMr3kV+AAdaKiPjiYMwbLRhuXnjICkWlTJjoHBCLDQeFzucGrqdXXpxPRyG579H/Qy+3mqquFFCHOn2NnBBoSfw7S9dGbn1XnSS+2W9dSAk=
