language: ruby
services:
- postgresql
before_script:
- psql -c 'create database teller_test;' -U postgres
deploy:
  provider: heroku
env:
  COINCAP_PATH: https://api.coincap.io
  SHAPESHIFT_PATH: https://shapeshift.io

  secure: "qEzD19M6ai12DdWW6vJ+leqMUXfuwbxE3Xf/IdgdtikfVBQqQmAynwYCCxpsYfiR8ndJi0ub2Y/mNprQ0CrR85Tu6xp0vyRfFMh1sX+IotlCt+irOmdSxYVU/OvjwrPupzRE6DqdH14wZgvshbGfyBY6rHJ0GnCZJ2L74Q3THuViZBtvO9lb2zvzVFi/n4M0KtipaGvbjcW146EcMy1sszT65fDhQTE+2KB/ZX00NfZHADWOdqXOB7/x9SRnPnGQMynSlWM2Chz8OSbg86DcWqNWmNBG+iVuz2tIcMSc0FvLpVUwfSKEPyS9/YgIEat56C4S9mduBoNsfmP+WVzM3XaPFmWDzzay8V8ZghB9DNwrdnvGMAYuVvysxhF+GkO8ftyAhDD30jyrmHlVIhz2u/w0BJ7HCeIzRSQK7HFYvuT6bwx6X25rcTR7dZzHy88m84fdQtnU1j+u/VRT0doSWGttJ4DasQDj5QQvSV3u02avec9TUMwwAzn3vUnS4PG4vrao3GC2pkJcyTLr0bCWOo5HorAt8vZeclvs8Lmy0Gm3AmYa0kDcl2xaedoGpUQYGNuOg9LZA6l5yy3/HhWWLaAbkCfoyCoWhCAt38iqJ8yGrbGAhP0tNcL4jv7VXTqDMqwMGEWVqAcDZB53sBX8XxjWDWb3Mz9qAsh5P3oepvI="
